### ISSUE TITLE
github actions build devenv from source instead of cache

### ISSUE THREAD

**Issue by kalekseev** [cachix/devenv#1065]
**Describe the bug**
Using steps from documentation:

```
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest
```

with latest updates devenv is not fetched from cache anymore:

```
building '/nix/store/hgk706h4i5qpb99q0a7n18q6cxdz52f2-devenv-1.0.1.drv'...
```

As a result each job with devenv setup in our CI is 5 minutes longer than before.
