### ISSUE TITLE
devenv test failing

### ISSUE THREAD

**Issue by jembishop** [cachix/devenv#1160]
I am trying to create a rust environment, and then run the `devenv test` command to verify it works on a CI job. When I set up the shell intitially it gave me this error:

```
 error:
       error: To use 'languages.rust.version', run the following command:

         $ devenv inputs add fenix github:nix-community/fenix --follows nixpkgs
```

So I ran the suggested command to get it to update the `devenv.yaml` and that seems to fix the `devenv shell` command.
However I still get this error when running `devenv test`, and I'm not sure how to fix it. Here is the version of devenv.yaml after the update:

```yaml
inputs:
  fenix:
    url: github:nix-community/fenix
    inputs:
      nixpkgs:
        follows: nixpkgs
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling

```

Here is my devenv.nix
```nix
{ pkgs, lib, ... }:

{
  languages.rust = {
    enable = true;
    channel = "stable";

    components = [ "rustc" "cargo" "clippy" "rustfmt" "rust-analyzer" ];
  };
  enterShell = ''
     source <(just --completions bash)
  '';
  enterTest = ''
    just init-project
  '';
  packages = [pkgs.just pkgs.pre-commit];
}
```

**Version**
 `devenv 1.0.4 (aarch64-darwin)`
