### ISSUE TITLE
Pyright, mypy not recognize poetry vens during pre-commit hook

### ISSUE THREAD

**Issue by ketamin00** [cachix/devenv#1234]
Im having trouble getting pyright to recoqnize my imports. Here is a simplified config
flake.nix
```nix
{
  inputs = {
    nixpkgs.url = "github:cachix/devenv-nixpkgs/rolling";
    systems.url = "github:nix-systems/default";
    devenv.url = "github:cachix/devenv";
    devenv.inputs.nixpkgs.follows = "nixpkgs";
  };

  nixConfig = {
    extra-trusted-public-keys = "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=";
    extra-substituters = "https://devenv.cachix.org";
  };

  outputs = { self, nixpkgs, devenv, systems, ... } @ inputs:
    let
      forEachSystem = nixpkgs.lib.genAttrs (import systems);
    in
    {
      packages = forEachSystem (system: {
        devenv-up = self.devShells.${system}.default.config.procfileScript;
      });

      devShells = forEachSystem
        (system:
          let
            pkgs = nixpkgs.legacyPackages.${system};
          in
          {
            default = devenv.lib.mkShell {
              inherit inputs pkgs;
              modules = [
	       ./devenv.nix
              ];
            };
          });
    };
}
```
devenv.nix
```nix
{...}:
{
  languages.python = {
  enable = true;
  poetry = {
    enable = true;
    install.enable = true;
    activate.enable = true;
    };
  };
  pre-commit.hooks = {
    pyright.enable = true;
  };
}
```

pyproject.toml
```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["ketamin00 <62392537+ketamin00@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.2"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Importing in a shell works just fine
```
➜  tmp git:(master) ✗ python
Python 3.11.8 (main, Feb  6 2024, 21:21:21) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastapi
>>> 
```

But if create a python file
main.py
```
from fastapi import FastAPI

app = FastAPI()
```

And run pre-commit hooks
```
➜  tmp git:(master) ✗ pre-commit run --all-files
pyright..................................................................Failed
- hook id: pyright
- exit code: 1

/home/user/dev/tmp/main.py
  /home/user/dev/tmp/main.py:1:6 - error: Import "fastapi" could not be resolved (reportMissingImports)
1 error, 0 warnings, 0 informations

```

Then pyright doesnt seem to recoqnize the imports. What am i doing wrong?

also, i am using direnv and nix-direnv
