### ISSUE TITLE
The option `languages.javascript.pnpm' does not exist

### ISSUE THREAD

**Issue by sandro-qiang** [cachix/devenv#1474]
**Describe the bug**
Do the first `devenv shell` after edit devenv.nix, the error shows up.

**To reproduce**
devenv.nix (in frontend folder)
```
{ pkgs, lib, ... }:

{
  languages.javascript = {
    enable = true;
    pnpm.enable = true;
    pnpm.install.enable = true;
  };
      
  tasks."build" = {
    exec = ''pnmp run build'';
  };
}
```

devenv.yaml (in project root)
```
inputs:
  nixpkgs:
    url: github:NixOS/nixpkgs/nixpkgs-unstable
  devenv:
    url: github:cachix/devenv/python-rewrite 
  nixpkgs-python:
    url: github:cachix/nixpkgs-python
    inputs:
      nixpkgs:
        follows: nixpkgs
imports:
  - ./frontend
  - ./backend
allowUnfree: true
```

error log
```
error:
       … while evaluating the attribute 'config'
         at «github:NixOS/nixpkgs/189e5f171b163feb7791a9118afa778d9a1db81f»/lib/modules.nix:334:9:
          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          335|         _module = checked (config._module);

       … while calling the 'seq' builtin
         at «github:NixOS/nixpkgs/189e5f171b163feb7791a9118afa778d9a1db81f»/lib/modules.nix:334:18:
          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       … while calling the 'throw' builtin
         at «github:NixOS/nixpkgs/189e5f171b163feb7791a9118afa778d9a1db81f»/lib/modules.nix:310:18:
          309|                     ''
          310|             else throw baseMsg
             |                  ^
          311|         else null;

       error:
       error: The option `languages.javascript.pnpm' does not exist. Definition values:
       - In `/home/user/works/myprj/frontend/devenv.nix':
           {
             enable = true;
             install = {
               enable = true;
             };
           ...
```

**Version**
 
devenv 1.1.0 (x86_64-linux)
