### ISSUE TITLE
Cargo does not handle `+toolchain` directives

### ISSUE THREAD

**Issue by mamcx** [cachix/devenv#1512]
**Describe the bug**

I tried to setup rust for cross-compiling to Android, and then try to build with:

```bash
devenv shell
cargo +nightly ndk --target=arm64-v8a build  -Zbuild-std
```

Get:

```
error: no such command: `+nightly`

	Cargo does not handle `+toolchain` directives.
	Did you mean to invoke `cargo` through `rustup` instead?
```

**To reproduce**

```nix
{ pkgs, ... }:

{
  # https://devenv.sh/basics/
  env.GREET = "devenv";

  # https://devenv.sh/packages/
  packages = [
    pkgs.git
    pkgs.libiconv
    pkgs.fastlane
    pkgs.nano
    pkgs.rustup # I try with this removed too.
  ];

  android = {
      enable = true;
      platforms.version = [ "34" ];
      systemImageTypes = [ "google_apis_playstore" ];
      abis = [ "arm64-v8a" "x86_64" ];
      cmdLineTools.version = "11.0";
      tools.version = "26.1.1";
      platformTools.version = "34.0.5";
      buildTools.version = [ "30.0.3" ];
      sources.enable = false;
      systemImages.enable = false;
      ndk.enable = true;
      ndk.version = [ "25.2.9519653" ];
      googleTVAddOns.enable = false;
      emulator.enable = false;
      extras = [ "extras;google;gcm" ];
      extraLicenses = [
        "android-sdk-preview-license"
#                        "android-googletv-license"
        "android-sdk-arm-dbt-license"
        "google-gdk-license"
        "intel-android-extra-license"
        "intel-android-sysimage-license"
        "mips-android-sysimage-license"
      ];
  };

  languages.python = {
    enable = true;
    version = "3.11";
  };

  languages.rust = {
    enable = true;
    components = ["rustc" "cargo" "clippy" "rustfmt" "rust-docs"];
    channel = "nightly";
    rustflags = "-Z threads=8";
    targets = [ 
      "x86_64-pc-windows-msvc"
      "x86_64-pc-windows-gnu"
      "x86_64-unknown-linux-musl"
      "aarch64-linux-android" 
      "arm-linux-androideabi" 
    ];
  };

  # https://devenv.sh/scripts/
  scripts.hello.exec = "echo hello from $GREET";

  enterShell = ''
      export ANDROID_HOME=$(which android | sed -E 's/(.*libexec\/android-sdk).*/\1/')
      export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653
      export ANDROID_SDK_ROOT=$ANDROID_NDK_HOME
      export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
  '';
}
```

```yaml
inputs:
  nixpkgs-python:
    url: github:cachix/nixpkgs-python
    inputs:
      nixpkgs:
        follows: nixpkgs
  nixpkgs:
    url: github:NixOS/nixpkgs/nixpkgs-unstable
  fenix:
    url: github:nix-community/fenix
    inputs:
      nixpkgs:
        follows: nixpkgs
allowUnfree: true
```

**Version**
 
devenv 1.3.0 (aarch64-darwin)
