### ISSUE TITLE
What to do to optimize CI?

### ISSUE THREAD

**Issue by mamcx** [cachix/devenv#1575]
I'm on Circleci and hope that moving to `devenv` improves my CI but takes longer instead.

Of course, I don't know exactly how to speed up the process.

So, is there a guideline on how to speed up this? What to cache? 

Now I have:

```yaml
commands:
  restore_cache_devenv:
    steps:
      - restore_cache:
          key: cache_devenv-v1-{{ arch }}-{{ checksum "devenv.lock" }}

  save_cache_devenv:
    steps:
      - save_cache:
          key: cache_devenv-v1-{{ arch }}-{{ checksum "devenv.lock" }}
          paths:
            - "./.devenv"

  setup_nix:
    description: "Setup nix environment"
    steps:
      - checkout
      - restore_cache_devenv
      - run:
          name: Install devenv
          command: |
            nix-env -iA devenv -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable
            devenv info
      - save_cache_devenv
```

**Comment by domenkozar** [comment]
@mamcx I assume most of the time you'd like to save is in `setup_nix`?

**Comment by byrnedo** [comment]
Also interested in this. 
Does caching the `.devenv` dirs help? I've been toying with it in github actions but getting some file not found errors.

**Comment by extrange** [comment]
I'm getting the same issue - devenv takes 7-8 minutes to setup the tests (running tests is fast). For reference my workflow file is

```yaml
name: Run devenv test
on:
  push:
  workflow_call:
    inputs:
      cache-size:
        required: false
        type: string
        default: 3G

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/devenv.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: ${{ inputs.cache-size }}

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Test # Most of the delay is here
        run: devenv test
```
