### ISSUE TITLE
Can't use script name if a shell alias with such name already exists

### ISSUE THREAD

**Issue by Andrew15-5** [cachix/devenv#1676]
**Describe the bug**
I have an `alias c`, but adding `scripts.c.exec` doesn't do anything, as the existing alias is not being overridden. I don't even know if it's possible to temporary `unalias` the thing in the devenv project and the restore it outside.

**To reproduce**

Have `alias c=something`

```nix
# devenv.nix
{ ... }:

{
  scripts.c.exec = "devenv tasks run typst:compile";
}
```

```yaml
# devenv.yaml
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
```

**Version**

devenv 1.3.1 (x86_64-linux)
