### ISSUE TITLE
have rust.toolchain respect rust-toolchain.toml

### ISSUE THREAD

**Issue by i-am-logger** [cachix/devenv#1707]
as an example this is how i use it with naersk

```toml
[toolchain]
channel = "nightly"
components = [ "rustc", "cargo", "rust-src" ]
profile = "minimal"```

```nix
    nixpkgs-mozilla = {
      url = "github:mozilla/nixpkgs-mozilla";
      flake = false;
    };


    pkgs = (import nixpkgs) {
    inherit system;

            overlays = [
              (import nixpkgs-mozilla)
            ];
          };

          toolchain =
            (pkgs.rustChannelOf {
              rustToolchain = ./rust-toolchain.toml;
              sha256 = "sha256-vFu6RmeJsrTgIjNjNJrC+pVZh1fgr0wm7VX24RJQ14k=";
            }).rust;


```
