### ISSUE TITLE
Using python3.13 and cachix taking too long in compiling

### ISSUE THREAD

**Issue by emdneto** [cachix/devenv#1709]
```
{ pkgs, ... }: {
  cachix.enable = true;
  languages.python = {
    enable = true;
    version = "3.13";
    venv.enable = true;
    uv.enable = true;
  };

  services.nginx = {
    enable = true;
    httpConfig = ''
      server {
        listen 8080;
        location / {
          return 200 "Hello, world!";
        }
      }
    '';
  };
  enterShell = ''
    echo "Hello, world! Shell"
  '';
  enterTest = ''
    wait_for_port 8080
    curl -s localhost:8080 | grep "Hello, world!"
  '';
}
```

```
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
  nixpkgs-python:
    url: github:cachix/nixpkgs-python
```

Every time I run the devenv shell, it compiles the python, taking too long to initialize the shell. How can I avoid that?  Already added `cachix use nixpkgs-python`

 ```
✔ Building shell in 354.6s.
• Entering shell
```
