### ISSUE TITLE
Tasks: Enforce Working Directory Option

### ISSUE THREAD

**Issue by rawkode** [cachix/devenv#1850]
I've started to explore the usage of devenv composition, like so:

```yaml
# yaml-language-server: $schema=https://devenv.sh/devenv.schema.json
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
  root:
    url: .
    flake: false

imports:
 - root/projects/rawkode.academy/platform
```

This works great in that my current devenv incorporates all the bits I need from the shared platform devenv, including tasks; which can also be used as dependencies. Love it.

Sometimes though, the inherited tasks need to be run from not the invoked working directory (most likely through CI when `devenv tasks run ci` is executed at the root of the repository and I'm composing all the child devends.

For this, it would be nice to specify that the working directory should be relative to the task itself:

```nix
{ pkgs, lib, config, inputs, ... }:

{
  packages = [ pkgs.bun ];

  tasks = {
    "db:generate-migrations" = {
      exec = "pwd";
      workdir = exec | file | "../path"
    };
  };
}
```

- exec would be wherever `devenv task run` is executed
- file would be the directory of the task definition
- a string would be a relative path from the task definition
