### ISSUE TITLE
Task Tags for Composed Environments

### ISSUE THREAD

**Issue by rawkode** [cachix/devenv#1851]
When I have a monorepo and I'm composing all my devenv's together at the root:

```yaml
# yaml-language-server: $schema=https://devenv.sh/devenv.schema.json
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
  root:
    url: .
    flake: false

imports:
 - root/projects/rawkode.academy/a
 - root/projects/rawkode.academy/b
 - root/projects/rawkode.academy/c
 - root/projects/rawkode.academy/d
```

It would be nice to run `devenv task run #ci` and it executes all tasks with a tag == ci:

```nix
{ pkgs, lib, config, inputs, ... }:

{
  packages = [ pkgs.bun ];

  tasks = {
    "db:generate-migrations" = {
      exec = "echo one";
      tags = [ "ci" ];
    };
  };
}
```
