### ISSUE TITLE
Allow `permittedInsecurePackages` to work globally

### ISSUE THREAD

**Issue by xav-ie** [cachix/devenv#1909]
Hello! Thank you maintainers for being awesome. I really love the simplicity of devenv.

I am facing issue where `permittedInsecurePackages` does not forward to other inputs and I am not sure how to workaround this now.

Here is my current devenv.nix:
```nix
{ ... }:
{
  languages = {
    ruby = {
      enable = true;
      version = "2.6.6";
    };
  };
}
```
And devenv.yaml:
```yaml
# yaml-language-server: $schema=https://devenv.sh/devenv.schema.json
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
  nixpkgs-ruby:
    # try using older version that did not have this error
    url: github:bobvanderlinden/nixpkgs-ruby/853db1f7f6af87322c18042af555194b1306172f
    inputs:
      nixpkgs:
        follows: nixpkgs

permittedInsecurePackages:
  - "openssl-1.1.1w"
```
Here is the error:
```
       error: Package ‘openssl-1.1.1w’ in «github:cachix/devenv-nixpkgs/c5208b594838ea8e6cca5997fbf784b7cca1ca90»/pkgs/development/libraries/openssl/default.nix:300 is marked as insecure, refusing to evaluate.


       Known issues:
        - OpenSSL 1.1 is reaching its end of life on 2023/09/11 and cannot be supported through the NixOS 23.11 release cycle. https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/

       You can install it anyway by allowing this package, using the
       following methods:

       a) To temporarily allow all insecure packages, you can use an environment
          variable for a single invocation of the nix tools:

            $ export NIXPKGS_ALLOW_INSECURE=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) for `nixos-rebuild` you can add ‘openssl-1.1.1w’ to
          `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
          like so:

            {
              nixpkgs.config.permittedInsecurePackages = [
                "openssl-1.1.1w"
              ];
            }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          ‘openssl-1.1.1w’ to `permittedInsecurePackages` in
          ~/.config/nixpkgs/config.nix, like so:

            {
              permittedInsecurePackages = [
                "openssl-1.1.1w"
              ];
            }
✖ Building shell in 2.19s
Error:   × Command `/nix/store/vaiiysmm0kp9prjzin56083kz0013cad-nix-2.24-devenv/bin/nix --show-trace --extra-
  │ experimental-features nix-command --extra-experimental-features flakes --option warn-dirty false
  │ --keep-going --max-jobs 8 --option eval-cache false --option extra-substituters https://
  │ devenv.cachix.org --option extra-trusted-public-keys devenv.cachix.org-
  │ 1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= print-dev-env --profile /home/x/Projects/
  │ aliceandbob/.devenv/gc/shell -vv --log-format internal-json` failed with with exit code 1

direnv: failed to build the devenv environment. devenv.nix may contain errors. see above.
```

I was able to "workaround" this by doing it myself. Here is workaround devenv.nix:
```nix
{
  pkgs,
  nixpkgs-ruby,
  ...
}:
{
  overlays = [
    (final: prev: {
      ruby = nixpkgs-ruby.packages.${prev.stdenv.system}."ruby-2.6.6".override {
        openssl = prev.openssl_1_1;
      };
    })
  ];

  languages = {
    ruby = {
      enable = true;
      package = pkgs.ruby;
    };
  };
}
```

Here is devenv.yaml:
```yaml
# yaml-language-server: $schema=https://devenv.sh/devenv.schema.json
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
  nixpkgs-ruby:
    url: github:bobvanderlinden/nixpkgs-ruby
    inputs:
      nixpkgs:
        follows: nixpkgs

permittedInsecurePackages:
  - "openssl-1.1.1w"
```

It "works"! I can enter the shell and it builds! --But then I get a weird error trying to run `bundle --version` (or any `bundle` command):
```
 bundle --version
Traceback (most recent call last):
        10: from /nix/store/z5qkr82yrla5sifxwlg04nn59f6d1qkg-bundler-2.6.6/bin/bundle:18:in `<main>'
         9: from /nix/store/z5qkr82yrla5sifxwlg04nn59f6d1qkg-bundler-2.6.6/bin/bundle:18:in `load'
         8: from /nix/store/z5qkr82yrla5sifxwlg04nn59f6d1qkg-bundler-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.6.6/exe/bundle:16:in `<top (required)>'
         7: from /nix/store/cy7ijwyniy8lih0jqpsg2wpv8894dq53-ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from /nix/store/cy7ijwyniy8lih0jqpsg2wpv8894dq53-ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from /nix/store/z5qkr82yrla5sifxwlg04nn59f6d1qkg-bundler-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.6.6/lib/bundler.rb:10:in `<top (required)>'
         4: from /nix/store/z5qkr82yrla5sifxwlg04nn59f6d1qkg-bundler-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.6.6/lib/bundler.rb:10:in `require_relative'
         3: from /nix/store/z5qkr82yrla5sifxwlg04nn59f6d1qkg-bundler-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.6.6/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'
         2: from /nix/store/z5qkr82yrla5sifxwlg04nn59f6d1qkg-bundler-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.6.6/lib/bundler/rubygems_ext.rb:460:in `<module:Gem>'
         1: from /nix/store/cy7ijwyniy8lih0jqpsg2wpv8894dq53-ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/nix/store/cy7ijwyniy8lih0jqpsg2wpv8894dq53-ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubygems/uri (LoadError)
```

So now I want to try the devenv version of this, hoping it would work better somehow, but I can't seem to get started on it working. Once I get it working, hopefully my main issue goes away. 

I think `permittedInsecurePacakges` would be simpler if it applied to all inputs, not just `pkgs`. You have to apply overrides to sub packages in order for it to work as seen in my "working" second devenv.nix. Someone better explains here what is happening:
https://github.com/bobvanderlinden/nixpkgs-ruby/issues/89#issuecomment-2278157289 

I tried to do an overlay override with the standard devenv.nix, but that did not work, it was overriding the standard ruby version :/, not the versioned one. I don't think you can apply overrides when using `version = "..."`, and the permit packages thing is not working, so now I am blocked.
