### ISSUE TITLE
How can I use older version of packages?

### ISSUE THREAD

**Issue by neonovic** [cachix/devenv#218]
Can you please advice me, how to achieve of PHP older versions?
Postgresql specific 12.1 version?
Elasticsearch 7.6 version?

I don't understand how to solve this. 
Thanks a lot.

**Comment by domenkozar** [comment]
That's in the scope of #15, I hope to have a prototype ready over the holidays

**Comment by shyim** [comment]
I guess for now you could override the derivation with your version and the src :)

**Comment by R-VdP** [comment]
**WARNING**: the procedure described below will give you old packages that might contain unmitigated security vulnerabilites, use at your own risk.

@neonovic if the versions you need were ever in nixpkgs, you can get them by importing an old revision of nixpkgs that contained the packages that you want.
You can find the last commit hash of nixpkgs containing a specific package version here: https://lazamar.co.uk/nix-versions/

And then, for instance for postgres 12.1, you can do something like this:

`devenv.yaml`:
```yaml
inputs:
  nixpkgs:
    url: nixpkgs
  nixpkgs-postgresql-12_1:
    # The commit hash was found with the website mentioned above
    url: github:nixos/nixpkgs/2158ec610d90359df7425e27298873a817b4c9dd
    # We are pre-flake era here...
    flake: false
```

`devenv.nix`:
```nix
{ inputs, pkgs, ... }:
{
  packages =
    let
      nixpkgs-postgresql-12_1 = import inputs.nixpkgs-postgresql-12_1 { };
    in
    [
      nixpkgs-postgresql-12_1.postgresql_12

      # For other packages, use the normal pkgs.<package> syntax,
      # so that they come from the up-to-date nixpkgs revision
    ];
}
```

We had to jump through some additional hoops here since that version is old enough that the last nixpkgs revision to contain it, did not have a `flake.nix` yet.
