### ISSUE TITLE
Provide a docker image

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#349]
```
FROM nixos/nix

RUN nix-env -iA cachix -f https://cachix.org/api/v1/install
RUN cachix use devenv
RUN nix-env -if https://github.com/cachix/devenv/tarball/v0.5
```

**Comment by mweinelt** [comment]
Would be helpful to have this to run on GitLab-CI.

**Comment by peteut** [comment]
@mweinelt 

For now I'm using `flake.nix` within the GitLab runner like this: 

```yaml
stages:
  - build

image: nixos/nix:latest

build-cli:
  stage: build
  script:
    - nix develop --experimental-features 'nix-command flakes' --impure --command bash "run-hooks"
    - nix develop --experimental-features 'nix-command flakes' --impure --command bash "build"
  tags:
    - docker
```
