### ISSUE TITLE
Use a local flake.nix as input

### ISSUE THREAD

**Issue by pigam** [cachix/devenv#404]
**I want to use a local flake as an input**

I found two problems:
- `url: .` is not accepted
- if I use a fullpath to the current directory, I got `error: found circular import of flake`.

**To Reproduce**
Create a projet with the files as in https://gist.github.com/pigam/095b15016cb8a30b4b28e317375e7d4b

**Version**
 
Paste here the output of `$ devenv version`.
`devenv: 0.5.1`

**Comment by domenkozar** [comment]
I think you'd need to use `url: path:.`, but that's not supported. I'd love to support this!

**Comment by therealpxc** [comment]
> I think you'd need to use `url: path:.`, but that's not supported. I'd love to support this!

To be clear, do you mean that relative paths are not supported here due to upstream Nix bugs, or that local paths are not supported for devenv flake inputs at all?

(I've run into a very strange issue where adding a repo as a local flake (with an absolute path) gives me a big stack trace, but adding the same input on GitHub does not.)

**Comment by domenkozar** [comment]
This might work with devenv 2.0

**Comment by OceangreenDev** [comment]
Hey, just wanted to check in, in case anyone else wants to use devenv with a local flake.
Here is a tiny example how I do this in my setup.
I also added an example how I follow the inputs of my local flake:

```text
.
├── flake.nix
├── devenv.nix
├── devenv.yaml
└── subproject/
    ├── devenv.nix
    └── devenv.yaml
```

`./devenv.yaml`:

```yaml
inputs:
  oceangreendevnix:
    url: "git+file:."
    flake: true
  treefmt-nix:
    follows: oceangreendevnix/treefmt-nix
    url: "github:numtide/treefmt-nix"
```

`./subproject/devenv.yaml`:

```yaml
imports:
  - /
inputs:
  oceangreendevnix:
    url: "git+file:.."
    flake: true
```

No guaranty that this is a good or even clean solution.
But it seems to work for me.

---

**Versions:**
devenv 2.2.1
nix (Nix) 2.34.8
