### ISSUE TITLE
Allow forcing users to use specified Cachix

### ISSUE THREAD

**Issue by shyim** [cachix/devenv#436]
It would be nice to have some kind of option to force people to use a specified cachix when the user has to built packages.

```nix
caches = [ "my-cache-name" ];
```

- In that way, you don't have to mutate your global nix config to add a specific cache
- You force users that this cache is being in use (when they forgot to do `cachix use xxx`)

**Comment by domenkozar** [comment]
Sounds good, I'll add it to the next release. Refs #244

**Comment by bobvanderlinden** [comment]
I made an issue very similar to this one, but it makes sesne to continue the conversation here.

I wanted to add to this issue also a way to handle non-cachix binary caches.

Some options to make this available in devenv.yaml:

* Combine with `inputs`, so that READMEs can just tell to add a single block of input to their `devenv.yaml`:
  
  ```yaml
  inputs:
    nixpkgs-ruby:
      url: https://github.com/bobvanderlinden/nixpkgs-ruby
      substituters:
        - https://nixpkgs-ruby.cachix.org
      public_keys:
        - "nixpkgs-ruby.cachix.org-1:vrcdi50fTolOxWCZZkw0jakOnUI1T19oYJ+PRYdK4SM="
  ```
* Add a separate section with substituters:

  ```yaml
  substituters:
  - url: https://nixpkgs-ruby.cachix.org
    public_key: "nixpkgs-ruby.cachix.org-1:vrcdi50fTolOxWCZZkw0jakOnUI1T19oYJ+PRYdK4SM="
  ```

* Scrap the whole concept of substituters and call is binary caches:

  ```yaml
  caches:
  - url: https://nixpkgs-ruby.cachix.org
    public_key: "nixpkgs-ruby.cachix.org-1:vrcdi50fTolOxWCZZkw0jakOnUI1T19oYJ+PRYdK4SM="
  ```

What also could be considered, but I imagine is a bit trickier, is to inherit `nixConfig` and/or cache configuration from `devenv.yaml` inputs. That way whenever `nixpkgs-ruby` changes its substituters and people update `nixpkgs-ruby` input, they will automatically be asked to add the new binary cache.

Currently the `nixConfig` that is in [`flake.nix`](https://github.com/bobvanderlinden/nixpkgs-ruby/blob/3319e158e168ddcac5e932e00884942a67a5979e/flake.nix#L7-L10) is defunct when not directly using `flake.nix`.
