### ISSUE TITLE
rust: unable to run rustfmt on newly created devenv project.

### ISSUE THREAD

**Issue by vic** [cachix/devenv#590]
**Describe the bug**

Created a new devenv project and enabled rust language support. The rustfmt binary seems to be present on the environment since it's part of the default toolchain, but trying to invoke it fails with an error. Same result when trying to run `cargo fmt`

![Screenshot 2023-05-12 at 13 34 18](https://github.com/cachix/devenv/assets/331/9bf0db2f-dc9e-4c66-9eb4-c65d0056f3d6)

Looking at this [rustfmt issue](https://github.com/rust-lang/rustfmt/issues/1707#issuecomment-310005652) it seems like a workaround is to set `LD_LIBRARY_PATH`, however as shown in the previous screenshot, the `LD_LIBRARY_PATH` as computed by devenv is correct `${DEVENV_PROFILE}/lib`, and also the offending dylib is present in that path. However I'm still not able to determine why rustfmt is unable to find it.

**To reproduce**

Enabled rust support via `languages.rust.enable = true;` and no other changes.

**Version**
 
devenv: 0.6.2
Environment is MacOS Ventura 13.3.1 (22E261) x86_64-darwin.

**Comment by vic** [comment]
Related issue https://github.com/cachix/devenv/pull/532

**Comment by vic** [comment]
Solved using nixpkgs stable 22.11 on `devenv.yaml` like this:

```yaml
inputs:
  nixpkgs:
    url: github:NixOS/nixpkgs/22.11
  fenix:
    url: github:nix-community/fenix
    inputs:
      nixpkgs:
        follows: nixpkgs
```

Now `cargo fmt` and `rustfmt` work as expected.
