### ISSUE TITLE
Package Sets

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#61]
It would be useful to be able to expose a package set in an environment, so that environments that import it can use a subset.

This would allow us to provide for example a set of all $lang tooling.

**Comment by domenkozar** [comment]
I was thinking about this a bit:

```yaml title="devenv.yaml"
inputs:
  nixpkgs:
    url: nixpkgs
pkgsets:
  pkgs:
    input: nixpkgs
    unfree: true
  mypkgs:
    input: xxx
```

Where they could then be automatically wired from flakes using `myflake.packages.${builtins.currentSystem}` or `exposedPackages` attribute in devenv.nix.

**Comment by domenkozar** [comment]
The other option would be to overload the inputs:

```yaml
inputs:
  nixpkgs:
    url: nixpkgs
    allowUnfree: true
  xxx:
    url: github:myorg/myrepo
    includeOverlays: true
    packages: mypkgs
```

**Comment by domenkozar** [comment]
A bit more explicit:

```yaml
inputs:
  nixpkgs:
    url: nixpkgs
    args:
      allowUnfree: true
  xxx:
    url: github:myorg/myrepo
    outputs:
      overlays: true
      packages: mypkgs
```
