### ISSUE TITLE
Unable to import .nix file from input

### ISSUE THREAD

**Issue by ankhers** [cachix/devenv#833]
**Describe the bug**

According to the documentation, I should be able to setup an input and then import a specific file from that input. Something like

```yaml
inputs:
  my_proj: ...
imports:
  - my_proj/foo.nix
```

However, when I try to do that I get an error saying that `my_proj/foo.nix/devenv.nix` is not found.

**To reproduce**

You can clone https://git.sr.ht/~ankhers/bar_service to see this happening. It is trying to import the `service.nix` file from https://git.sr.ht/~ankhers/foo_service

**Version**
 
```sh
❯ devenv version
devenv 1.0 (x86_64-linux)
```

**Comment by domenkozar** [comment]
It will be possible after #745 using:

```
inputs:
  root:
    url: git+file://.
    flake: false
imports:
- root/foo_service
```
