### ISSUE TITLE
How to reference a package defined in a imported devenv for a pre-commit hook?

### ISSUE THREAD

**Issue by jashandeep-sohi** [cachix/devenv#871]
Say I have a remote devenv that defines a custom package:

```nix
{ pkgs, lib, ... }:

let
 mypkg = import ./mypkg.nix { inherit pkgs lib; };
in
{
  packages = [
    pkgs.git
    mypkg
  ];
}

```

And then I import this devenv into another where the `devenv.yaml` looks like:

```yaml
inputs:
  nixpkgs:
    url: github:NixOS/nixpkgs/nixpkgs-unstable
  myimport:
    url: git+https://github.com/myusername/mydevenv
imports:
  - myimport
```

How do I go about referencing a binary file built by mypackage in a pre-commit hook?

```nix
{ pkgs, inputs, ... }:
{

  packages = [
    pkgs.git
  ];

  pre-commit.hooks = {
    custom-hook = {
      enable = true;
      name = "Do something";
      entry = "${inputs.myimport}/mypackage-bin .... ??";
    };

  };

}
```

BTW, I can reference `mypackage-bin` just fine when in a `devenv shell`. But the pre-commit hook can't. Which is why I am trying to refer to it explicitly.
