### ISSUE TITLE
using services.mongob.enable results in a need to compile MongoDB

### ISSUE THREAD

**Issue by mcdonc** [cachix/devenv#916]
**Describe the bug**

It seems like doing ``services.mongodb.enable`` should result in a MongoDB that comes from cache.nixos.org, but instead it must be recompiled.
 
**To reproduce**

``services.mongodb.enable = true``

**Version**
 
python-rewrite branch.

Here's devenv.yaml:

```
inputs:
  nixpkgs:
    url: github:NixOS/nixpkgs/nixos-23.11
  nixpkgs-python:
    url: github:cachix/nixpkgs-python
  nix2container:
    url: github:nlewo/nix2container
    inputs:
      nixpkgs:
        follows: nixpkgs
  mk-shell-bin:
    url: github:rrbutani/nix-mk-shell-bin
  devenv:
    url: github:mcdonc/devenv/python-rewrite-no-manylinux
#    url: path:/home/chrism/projects/devenv/src/modules
  overlays:
    url: path:./overlays
    overlays:
      - default

allowUnfree: true
permittedInsecurePackages:
  - openssl-1.1.1w
```
