### ISSUE TITLE
mono repo importing

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#998]
With #745 it will be possible to import devenv.nix across directories in a git repo.

But it's a bit cumbersome to use:

```
inputs:
  root:
    url: git+file://.
    flake: false
imports:
- root/examples/compose/projectA
```

I wonder if we should come up with something like `root://` to support imports from top-level of the git repo.
